services:
  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./client:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    env_file:
      - .env

  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./server/src:/app/src
      - ./server/prisma:/app/prisma
    stdin_open: true
    tty: true
    depends_on:
      - database
    env_file:
      - .env

  database:
    image: postgres:16
    container_name: daurnchess-db
    restart: always
    environment:
      POSTGRES_USER: daurn
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: daurnchess
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
