services:
  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
    stdin_open: true
    tty: true

  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./server:/app
    stdin_open: true
    tty: true
